name: CI

on: [pull_request]

jobs:
  stylelint-eslint-typecheck-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install yarn
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Run stylelint
        run: yarn stylelint
      - name: Run lint
        run: yarn lint
      - name: Run typecheck
        run: yarn typecheck
      - name: Run test
        run: yarn test:ci
